# Generated by Django 4.0.6 on 2022-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0002_doctormodel_administratormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='profile_set',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
    ]
