# Generated by Django 4.0.6 on 2022-07-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('precocare', '0003_doctormodel_profile_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=500, null=True)),
                ('contact1', models.CharField(max_length=50, null=True)),
                ('contact2', models.CharField(max_length=50, null=True)),
                ('emial', models.CharField(max_length=50, null=True)),
                ('about_clinic', models.TextField(blank=True)),
                ('street', models.CharField(max_length=500, null=True)),
                ('province', models.CharField(max_length=500, null=True)),
                ('suburb', models.CharField(max_length=500, null=True)),
                ('mon_fri_hours', models.CharField(max_length=500, null=True)),
                ('saturday', models.CharField(max_length=500, null=True)),
                ('sunday', models.CharField(max_length=500, null=True)),
                ('holidays', models.CharField(max_length=500, null=True)),
                ('clinic_type', models.CharField(max_length=100, null=True)),
                ('profile_set', models.CharField(blank=True, default='No', max_length=50, null=True)),
                ('clinic_status', models.CharField(blank=True, default='clinic_disabled', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('clinic_admins', models.ManyToManyField(default=None, related_name='admins', to='precocare.administratormodel')),
                ('clinic_doctors', models.ManyToManyField(blank=True, default=None, related_name='physicians', to='precocare.doctormodel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
