# Generated by Django 4.0.6 on 2022-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0006_insurancemodel_servicelistedmodel_servicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodel',
            name='insurance_cover',
            field=models.ManyToManyField(blank=True, default=None, related_name='medical_scheme', to='precocare.insurancemodel'),
        ),
    ]
