# Generated by Django 4.0.6 on 2022-07-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0007_clinicmodel_insurance_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuburbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLocationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=1000, null=True)),
                ('province', models.CharField(max_length=1000, null=True)),
                ('suburb', models.CharField(max_length=1000, null=True)),
                ('street', models.CharField(max_length=1000, null=True)),
                ('zipcode', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('clinic_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_location', to='precocare.clinicmodel')),
            ],
        ),
    ]
