# Generated by Django 4.0.6 on 2022-07-28 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0008_provincemodel_suburbmodel_cliniclocationsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratormodel',
            name='precocare_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicmodel',
            name='clinic_status',
            field=models.CharField(blank=True, default='Disabled', max_length=200, null=True),
        ),
    ]
