# Generated by Django 4.0.6 on 2022-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0009_administratormodel_precocare_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratormodel',
            name='precocare_id',
        ),
        migrations.AddField(
            model_name='administratormodel',
            name='user_identification',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
