# Generated by Django 4.0.6 on 2022-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0010_remove_administratormodel_precocare_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='doctor_license',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
