# Generated by Django 4.0.6 on 2022-07-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0011_doctormodel_doctor_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=500, null=True)),
                ('service_fee', models.CharField(max_length=500, null=True)),
                ('clinic_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_service', to='precocare.doctormodel')),
            ],
        ),
    ]
