# Generated by Django 4.0.6 on 2022-07-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0012_doctorservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorservices',
            old_name='clinic_id',
            new_name='doctor_id',
        ),
    ]
