# Generated by Django 4.0.6 on 2022-08-02 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('precocare', '0014_alter_administratormodel_profile_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_status', models.CharField(blank=True, max_length=50, null=True)),
                ('application_for', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_appointment', models.CharField(blank=True, max_length=500, null=True)),
                ('reschedule_date', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_surname', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=500, null=True)),
                ('identification', models.CharField(blank=True, max_length=13, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('street', models.CharField(blank=True, max_length=1000, null=True)),
                ('town', models.CharField(blank=True, max_length=1000, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_status', models.CharField(blank=True, default='Outstanding', max_length=100, null=True)),
                ('reason_visit', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('application_status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('notify', models.CharField(blank=True, default='Incomplete', max_length=100, null=True)),
                ('User', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to=settings.AUTH_USER_MODEL)),
                ('clinic_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_application', to='precocare.clinicmodel')),
                ('doctor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_application', to='precocare.doctormodel')),
                ('medical_aid', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='application_medical', to='precocare.insurancemodel')),
                ('service', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='application_service', to='precocare.servicemodel')),
            ],
        ),
    ]
