# Generated by Django 4.0.6 on 2022-08-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0015_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_application', to='precocare.doctormodel'),
        ),
    ]
