# Generated by Django 4.0.6 on 2022-08-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0017_alter_applicationform_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='clinic_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_chosen', to='precocare.cliniclocationsmodel'),
        ),
    ]
