# Generated by Django 4.0.6 on 2022-08-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0018_applicationform_clinic_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='cancel_appointment',
            field=models.CharField(blank=True, default='Ongoing', max_length=100, null=True),
        ),
    ]
