# Generated by Django 4.0.6 on 2022-08-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0019_applicationform_cancel_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='patient_file_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
