# Generated by Django 4.0.6 on 2022-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0020_applicationform_patient_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='gender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
