# Generated by Django 4.0.6 on 2022-08-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0022_applicationform_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicTimeSlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(blank=True, max_length=1000, null=True)),
                ('clinic_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_timeslot', to='precocare.clinicmodel')),
                ('service', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_timeslot', to='precocare.servicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTimeslotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.CharField(blank=True, default='Pending', max_length=1000, null=True)),
                ('date', models.DateField()),
                ('date_field', models.CharField(blank=True, max_length=1000, null=True)),
                ('clinic_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_clinic', to='precocare.clinicmodel')),
                ('clinic_timeslot_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_timeslot', to='precocare.clinictimeslotmodel')),
            ],
        ),
    ]
