# Generated by Django 4.0.6 on 2022-08-05 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('precocare', '0025_applicationform_time_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtimeslotmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timeslot', to=settings.AUTH_USER_MODEL),
        ),
    ]
