# Generated by Django 4.0.6 on 2022-08-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0027_alter_applicationform_time_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='time_slot_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_pk', to='precocare.bookedtimeslotmodel'),
        ),
    ]
