# Generated by Django 4.0.6 on 2022-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0029_doctormodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='files/doctorprofile'),
        ),
    ]
