# Generated by Django 4.0.6 on 2022-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0030_alter_doctormodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodel',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/clinics'),
        ),
        migrations.AddField(
            model_name='clinicmodel',
            name='sub_image1',
            field=models.ImageField(blank=True, null=True, upload_to='files/clinics'),
        ),
        migrations.AddField(
            model_name='clinicmodel',
            name='sub_image2',
            field=models.ImageField(blank=True, null=True, upload_to='files/clinics'),
        ),
        migrations.AddField(
            model_name='clinicmodel',
            name='sub_image3',
            field=models.ImageField(blank=True, null=True, upload_to='files/clinics'),
        ),
    ]
