# Generated by Django 4.0.6 on 2022-08-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0031_clinicmodel_hero_image_clinicmodel_sub_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='date_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
