# Generated by Django 4.0.6 on 2022-08-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0032_alter_applicationform_date_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300, null=True)),
                ('review', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='precocare.doctormodel')),
            ],
        ),
    ]
