# Generated by Django 4.0.6 on 2022-08-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0033_doctorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_upvote', to='precocare.doctormodel')),
            ],
        ),
    ]
