# Generated by Django 4.0.6 on 2022-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0034_doctorupvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoCareComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
