# Generated by Django 4.0.6 on 2022-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0036_clinicmodel_online_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='admin_booked',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
