# Generated by Django 4.0.6 on 2022-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0038_cliniclocationsmodel_contact1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodel',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
