# Generated by Django 4.0.6 on 2022-09-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precocare', '0039_clinicmodel_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='time_slot_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slot_pk', to='precocare.bookedtimeslotmodel'),
        ),
    ]
